name: CI

# ON a PUSH to the BRANCH MASTER
on:
  push:
    branches: [ production ]

# Run these JOBS
jobs:
  # This workflow contains a single job called "build"
  build:
    # Run on an UBUNTU-LATEST container
    runs-on: ubuntu-latest

    # Run these STEPS in order
    steps:

    - name: Output PHP version
      run: php --version

    - name: Output AWS CLI version
      run: aws --version

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Do a COMPOSER INSTALL
    - uses: php-actions/composer@v1

    - name: Run the unit tests
      run: make test

    - name: Clear Laravel's cache
      run: php artisan cache:clear

    - name: Deploy the PHP part
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # NPM CI installs dependencies specifically for a CI environment
    - name: Install JS dependencies
      run: npm ci

    - name: Deploy the static part
      run: make static
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
