name: CI

# ON a PUSH to the BRANCH MASTER
on:
  push:
    branches: [ master ]

# Run these JOBS
jobs:
  # This workflow contains a single job called "build"
  build:
    # Run on an UBUNTU-LATEST container
    runs-on: ubuntu-latest

    # Run these STEPS in order
    steps:

    - name: Output PHP version
      run: php --version

    - name: Output AWS CLI version
      run: aws --version

    # Install Serverless framework globally
    - uses: serverless/github-action@master

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Do a COMPOSER INSTALL
    - uses: php-actions/composer@v1

    # NPM CI installs dependencies specifically for a CI environment
    - name: Install JS dependencies
      run: npm ci

    # Run out makefile from within the repository
    - name: Deploy to AWS infrastructure
      run: make deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Say something
      run: echo 'Finished!'
